### ISSUE TITLE
the file dosent exists

### ISSUE THREAD

**Issue by rockdrigo** [janatzend/vagrant-zendserver-nginx-php5.5#1]
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

http://s3-eu-west-1.amazonaws.com/zend-de-vagrant-boxes/ubuntu14.04-x64-zendserver8.0-nginx-php5.5.box

**Comment by janatzend** [comment]
This repository is not actively supported by me anymore. I should have marked this in the README. Sorry about that...

However, you're requesting an old version of Zend Server with an unsupported PHP. If you really want to work with this box, I think I can find a way provide it to you. On the other hand I highly recommend to work with Zend Server 8.5 or higher with PHP 5.6 or higher. Zend Server 8.5 provides PHP 5.6 support until 2020.

Maybe you also want to check out my Zend Server Docker repo https://github.com/janatzend/docker-zendserver resp. the ready to use container on Docker hub: https://hub.docker.com/r/janatzend/zend-server/

**Comment by rockdrigo** [comment]
thanks for the explanation, i never work with docker before, but i think that this is a good time to see how it works :D thanks for all!!!
